### PR TITLE
Added RFM95W/96W/98W

### PR DESCRIPTION
**Pull request by Frigyes06**
##### SUMMARY
Added RFM95W/96W/98W module

##### DATASHEETS / REFERENCES
[datasheet](https://www.hoperf.com/data/upload/portal/20190801/RFM95W-V2.0.pdf)

##### CHECKLIST

- [X] I have read and followed the library conventions¹.
- [ ] For packages, I followed IPC7351C (see details in library conventions).
- [ ] For modified elements, I bumped their version number².
- [X] I already used the new library elements in a design and verified their correctness (optional).
- [X] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [X] I agree to publish all my changes under the CC0 Public Domain License³, allowing everyone to use and modify the content without any restrictions.

¹ *Library Conventions: https://docs.librepcb.org/#libraryconventions*
² *Minor version bump if only metadata was modified (e.g. "0.1" -> "0.1.1"), major version bump if functional changes were made (e.g. "0.1" -> "0.2")*
³ *CC0 Public Domain License: https://en.wikipedia.org/wiki/CC0*

### CODE REVIEW

**Comment by ubruhin** [comment]
Looks pretty good to me! :slightly_smiling_face: Just some minor comments:

- The component category should be removed from this PR - generic categories shall only be added to the "LibrePCB Base" library - but in this case, I'd suggest to just re-use the already existing category "Integrated Circuits - Interface - Drivers, Receivers, Transmitters" since the similar RF module RN2483 also uses that category.
- The package category should also be removed because it is generic - however, in this case you could move it into the parent category "Manufacturer-Specific" and rename it to "HopeRF". Then it would be fine.
- Symbol: Usually when GND/VCC have a distance of 2 grids (which is great!), we also keep 2 grids distance between GND and the next  pin (MISO in this case) to keep a visual separation between power and I/O pins. I'd thus make the symbol 2.54mm higher to add this separation (and move ANT to the bottom then, having  3 grids distance to DIO5).
- Component: Might be nice to mark mandatory signals as "required" (checkbox) to ensure the ERC raises an error if any mandatory signal is not connected.
- Package:
  - Generally any orientation marking on the placement layer ("IC" in this case) should be *outside* the package to allow verifying the orientation *after* assembling it (manual optical inspection). And for such PCB modules, the silkscreen below it might even lead to an uneven assembly due to the thickness of the silkscreen(?). I think in this case I'd change the "IC" to the documentation layer to still see it in the assembly drawing, but without having a negative impact on the assembly. And then extend the placement layer line at the top left to have a pad-1 marking on the silkscreen.
  - The placement polygon overlaps with the documentation polygon - according our library conventions, the placement polygon must be fully *outside* of the device.
- Device: Generally a device should clearly refer to a part which can be bought. This means RFM95W, RFM96W and RFM98W should be three separate devices, not only one. Then you'll also get a BOM with a clear part number to order. Just use the "Duplicate" context menu item in the library editor, it allows to duplicate the whole device including pinout.

You might also want to take a look at the similar device "RN2483" in the Microchip library - especially the package there is pretty nice (see for example the pad-1 marking).

**Comment by Frigyes06** [comment]
Thank you for your detailed feedback!
I'll make the necessary changes based on your recomendations as soon as I can!

**Comment by Frigyes06** [comment]
I think all should be fixed now.

**Comment by ubruhin** [comment]
Thanks for the update! Unfortunately I found some more things which needed to be changed, thus I added a commit to fix these things:

- Fixed package pad numbering (pads 9-16 were numbered the wrong way around)
- Fixed documentation/outline polygons which still had several issues
- Renamed RST pin to RESET as documented in datasheet
- Set DIO0 and DIO1 as **not** required (I don't see any hint in the datasheet that these pins need to be connected)
- Re-arranged symbol pins to be more consistent with the pin order usually used for SPI (SCK, MOSI, MISO, SS)
- Changed symbol category because it was still invalid

image

I hope this is fine for you. If you don't insist, I'll merge this soon :slightly_smiling_face:

**Comment by Frigyes06** [comment]
Thank you for the fixes!

**Pull request merged**
